package View;

import Model.LoginModel;
import Controller.LoginController;
import Database.DatabaseConnector;
import com.lowagie.text.Document;
import com.lowagie.text.DocumentException;
import com.lowagie.text.pdf.PdfPTable;
import com.lowagie.text.pdf.PdfWriter;
import java.awt.event.KeyEvent;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class CashierView extends javax.swing.JFrame {

    private double total = 0.0;
    private DefaultTableModel dataModelInvoice;

    /**
     * Creates new form Cashier
     */
    public CashierView() {
        initComponents();
        dataModelInvoice = new DefaultTableModel(new String[]{"ItemID", "Name", "Category", "Qty", "Price"}, 0);
        tblInv.setModel(dataModelInvoice);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlBG = new javax.swing.JPanel();
        pnlFooter = new javax.swing.JPanel();
        lblFooter = new javax.swing.JLabel();
        pnlInvoice = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblInv = new javax.swing.JTable();
        lblInvoice = new javax.swing.JLabel();
        btnPrint = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();
        txtTotal = new javax.swing.JTextField();
        txtPay = new javax.swing.JTextField();
        txtBal = new javax.swing.JTextField();
        btnPay = new javax.swing.JButton();
        lblTotal = new javax.swing.JLabel();
        lblPay = new javax.swing.JLabel();
        lblBal = new javax.swing.JLabel();
        btnCal = new javax.swing.JButton();
        btnRemove = new javax.swing.JButton();
        lblPayErr = new javax.swing.JLabel();
        pnlProducts = new javax.swing.JPanel();
        btnLogin = new javax.swing.JButton();
        btnRef = new javax.swing.JButton();
        txtSearch = new javax.swing.JTextField();
        btnSearch = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblPro = new javax.swing.JTable();
        btnView = new javax.swing.JButton();
        btnAdd = new javax.swing.JButton();
        lblProducts = new javax.swing.JLabel();
        spnQty = new javax.swing.JSpinner();
        lblQty = new javax.swing.JLabel();
        pnlHeader = new javax.swing.JPanel();
        lblHeader = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Apple iStore - Cashier Dashboard");
        setResizable(false);

        pnlBG.setBackground(new java.awt.Color(0, 0, 51));

        pnlFooter.setBackground(new java.awt.Color(51, 102, 255));

        lblFooter.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        lblFooter.setForeground(new java.awt.Color(255, 255, 255));
        lblFooter.setText("Apple Technologies USA");

        javax.swing.GroupLayout pnlFooterLayout = new javax.swing.GroupLayout(pnlFooter);
        pnlFooter.setLayout(pnlFooterLayout);
        pnlFooterLayout.setHorizontalGroup(
            pnlFooterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlFooterLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblFooter)
                .addGap(377, 377, 377))
        );
        pnlFooterLayout.setVerticalGroup(
            pnlFooterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlFooterLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblFooter)
                .addContainerGap())
        );

        pnlInvoice.setBackground(new java.awt.Color(51, 153, 255));

        tblInv.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ItemID", "Name", "Category", "Quantity", "Price($)"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblInv.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jScrollPane2.setViewportView(tblInv);

        lblInvoice.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        lblInvoice.setForeground(new java.awt.Color(255, 255, 255));
        lblInvoice.setText("Invoice Details Table");

        btnPrint.setFont(new java.awt.Font("Segoe UI", 3, 13)); // NOI18N
        btnPrint.setForeground(new java.awt.Color(0, 51, 255));
        btnPrint.setText("Print Invoice");
        btnPrint.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnPrint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrintActionPerformed(evt);
            }
        });

        btnExit.setFont(new java.awt.Font("Segoe UI", 3, 13)); // NOI18N
        btnExit.setForeground(new java.awt.Color(0, 51, 255));
        btnExit.setText("Exit");
        btnExit.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });

        txtTotal.setEditable(false);
        txtTotal.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        txtPay.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtPayKeyPressed(evt);
            }
        });

        txtBal.setEditable(false);

        btnPay.setFont(new java.awt.Font("Segoe UI", 3, 13)); // NOI18N
        btnPay.setForeground(new java.awt.Color(0, 51, 255));
        btnPay.setText("Pay");
        btnPay.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnPay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPayActionPerformed(evt);
            }
        });

        lblTotal.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        lblTotal.setForeground(new java.awt.Color(255, 255, 255));
        lblTotal.setText("Total ($) :");

        lblPay.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        lblPay.setForeground(new java.awt.Color(255, 255, 255));
        lblPay.setText("Payment ($) :");

        lblBal.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        lblBal.setForeground(new java.awt.Color(255, 255, 255));
        lblBal.setText("Balance ($) :");

        btnCal.setFont(new java.awt.Font("Segoe UI", 3, 13)); // NOI18N
        btnCal.setForeground(new java.awt.Color(0, 51, 255));
        btnCal.setText("Calculate Balance");
        btnCal.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnCal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalActionPerformed(evt);
            }
        });

        btnRemove.setFont(new java.awt.Font("Segoe UI", 3, 13)); // NOI18N
        btnRemove.setForeground(new java.awt.Color(0, 51, 255));
        btnRemove.setText("Remove From Invoice");
        btnRemove.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnRemove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoveActionPerformed(evt);
            }
        });

        lblPayErr.setFont(new java.awt.Font("Consolas", 1, 13)); // NOI18N
        lblPayErr.setForeground(new java.awt.Color(0, 0, 204));

        javax.swing.GroupLayout pnlInvoiceLayout = new javax.swing.GroupLayout(pnlInvoice);
        pnlInvoice.setLayout(pnlInvoiceLayout);
        pnlInvoiceLayout.setHorizontalGroup(
            pnlInvoiceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlInvoiceLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(pnlInvoiceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlInvoiceLayout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(lblInvoice)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlInvoiceLayout.createSequentialGroup()
                        .addGroup(pnlInvoiceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 558, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(pnlInvoiceLayout.createSequentialGroup()
                                .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnRemove, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnPrint, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(46, 46, 46)
                        .addGroup(pnlInvoiceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlInvoiceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlInvoiceLayout.createSequentialGroup()
                                    .addGroup(pnlInvoiceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lblTotal, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(lblPay, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(lblBal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(pnlInvoiceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(txtPay, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(txtTotal, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(txtBal, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addComponent(lblPayErr, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnlInvoiceLayout.createSequentialGroup()
                                .addComponent(btnCal, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnPay, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(28, 28, 28))))
        );
        pnlInvoiceLayout.setVerticalGroup(
            pnlInvoiceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlInvoiceLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblInvoice)
                .addGroup(pnlInvoiceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlInvoiceLayout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(pnlInvoiceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblTotal))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pnlInvoiceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblPay)
                            .addComponent(txtPay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(9, 9, 9)
                        .addComponent(lblPayErr, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pnlInvoiceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtBal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblBal)))
                    .addGroup(pnlInvoiceLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(pnlInvoiceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnExit)
                    .addComponent(btnRemove)
                    .addComponent(btnPrint)
                    .addComponent(btnCal)
                    .addComponent(btnPay))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        pnlInvoiceLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnCal, btnPay});

        pnlInvoiceLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {lblPayErr, txtPay});

        pnlProducts.setBackground(new java.awt.Color(102, 153, 255));

        btnLogin.setFont(new java.awt.Font("Segoe UI", 3, 13)); // NOI18N
        btnLogin.setForeground(new java.awt.Color(0, 51, 255));
        btnLogin.setText("Back to Login");
        btnLogin.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });

        btnRef.setFont(new java.awt.Font("Segoe UI", 3, 13)); // NOI18N
        btnRef.setForeground(new java.awt.Color(0, 51, 255));
        btnRef.setText("Refresh");
        btnRef.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnRef.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefActionPerformed(evt);
            }
        });

        btnSearch.setFont(new java.awt.Font("Segoe UI", 3, 13)); // NOI18N
        btnSearch.setForeground(new java.awt.Color(0, 51, 255));
        btnSearch.setText("Search");
        btnSearch.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        tblPro.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ItemID", "Name", "Category", "Quantity", "Price($)"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblPro.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jScrollPane1.setViewportView(tblPro);

        btnView.setFont(new java.awt.Font("Segoe UI", 3, 13)); // NOI18N
        btnView.setForeground(new java.awt.Color(0, 51, 255));
        btnView.setText("View Products");
        btnView.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewActionPerformed(evt);
            }
        });

        btnAdd.setFont(new java.awt.Font("Segoe UI", 3, 13)); // NOI18N
        btnAdd.setForeground(new java.awt.Color(0, 51, 255));
        btnAdd.setText("Add to Invoice");
        btnAdd.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        lblProducts.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        lblProducts.setForeground(new java.awt.Color(255, 255, 255));
        lblProducts.setText("Product Details Table");

        spnQty.setModel(new javax.swing.SpinnerNumberModel(1, 1, 10000, 1));
        spnQty.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        lblQty.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        lblQty.setForeground(new java.awt.Color(255, 255, 255));
        lblQty.setText("Add The Quantity :");

        javax.swing.GroupLayout pnlProductsLayout = new javax.swing.GroupLayout(pnlProducts);
        pnlProducts.setLayout(pnlProductsLayout);
        pnlProductsLayout.setHorizontalGroup(
            pnlProductsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlProductsLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(pnlProductsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnlProductsLayout.createSequentialGroup()
                        .addComponent(lblQty)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(spnQty, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlProductsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(lblProducts)
                        .addGroup(pnlProductsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 860, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(pnlProductsLayout.createSequentialGroup()
                                .addComponent(btnLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnView, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnRef, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlProductsLayout.setVerticalGroup(
            pnlProductsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlProductsLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(pnlProductsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSearch)
                    .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRef)
                    .addComponent(btnLogin)
                    .addComponent(btnView))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblProducts)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(pnlProductsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(spnQty, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAdd)
                    .addComponent(lblQty))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        pnlHeader.setBackground(new java.awt.Color(0, 102, 255));

        lblHeader.setFont(new java.awt.Font("Segoe UI", 1, 17)); // NOI18N
        lblHeader.setForeground(new java.awt.Color(255, 255, 255));
        lblHeader.setText("iStore - Cashier Dashboard");

        javax.swing.GroupLayout pnlHeaderLayout = new javax.swing.GroupLayout(pnlHeader);
        pnlHeader.setLayout(pnlHeaderLayout);
        pnlHeaderLayout.setHorizontalGroup(
            pnlHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlHeaderLayout.createSequentialGroup()
                .addGap(346, 346, 346)
                .addComponent(lblHeader)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlHeaderLayout.setVerticalGroup(
            pnlHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlHeaderLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblHeader)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pnlBGLayout = new javax.swing.GroupLayout(pnlBG);
        pnlBG.setLayout(pnlBGLayout);
        pnlBGLayout.setHorizontalGroup(
            pnlBGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBGLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlBGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlInvoice, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlProducts, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlHeader, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlFooter, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        pnlBGLayout.setVerticalGroup(
            pnlBGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBGLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlHeader, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlProducts, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlInvoice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlFooter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlBG, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlBG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        getAccessibleContext().setAccessibleName("iStore - Cashier Dashboard");

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        LoginView login = new LoginView();
        login.setVisible(true);

        LoginModel loginModel = new LoginModel();

        LoginController logincontroller = new LoginController(login, loginModel);
        logincontroller.initializeController();
        this.dispose();
    }//GEN-LAST:event_btnLoginActionPerformed

    private void btnRefActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefActionPerformed
        CashierView cashier = new CashierView();
        cashier.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnRefActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        performSearch();
    }

    private void performSearch() {
        if (txtSearch.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Search Box is Empty!");
        } else {
            try {
                Class.forName("com.mysql.cj.jdbc.Driver");
                Connection con = DatabaseConnector.connect();

                String sql = "SELECT * FROM products WHERE name LIKE ? OR itemid LIKE ? OR category LIKE ?";
                try (PreparedStatement ps = con.prepareStatement(sql)) {
                    ps.setString(1, "%" + txtSearch.getText() + "%");
                    ps.setString(2, "%" + txtSearch.getText() + "%");
                    ps.setString(3, "%" + txtSearch.getText() + "%");

                    ResultSet rs = ps.executeQuery();

                    DefaultTableModel tblModel = (DefaultTableModel) tblPro.getModel();
                    tblModel.setRowCount(0);

                    while (rs.next()) {
                        String id = String.valueOf(rs.getInt("ItemID"));
                        String name = rs.getString("Name");
                        String category = rs.getString("Category");
                        String qty = rs.getString("Qty");
                        String price = rs.getString("Price");

                        String tbData[] = {id, name, category, qty, price};
                        tblModel.addRow(tbData);
                    }
                }
                con.close();
            } catch (ClassNotFoundException | SQLException e) {

            }
        }
    }//GEN-LAST:event_btnSearchActionPerformed

    private boolean isItemInInvoice(String itemID) {
        for (int i = 0; i < tblInv.getRowCount(); i++) {
            String existingItemID = (String) tblInv.getValueAt(i, 0);
            if (itemID.equals(existingItemID)) {
                return true;
            }
        }
        return false;
    }

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        int selectedRow = tblPro.getSelectedRow();

        if (selectedRow != -1) {
            try {
                String itemID = (String) tblPro.getValueAt(selectedRow, 0);
                String name = (String) tblPro.getValueAt(selectedRow, 1);
                String category = (String) tblPro.getValueAt(selectedRow, 2);
                String qtyString = (String) tblPro.getValueAt(selectedRow, 3);
                double price = Double.parseDouble((String) tblPro.getValueAt(selectedRow, 4));

                int qtyToAdd = (int) spnQty.getValue();
                int qtyFromTable = Integer.parseInt(qtyString);

                if (qtyToAdd <= qtyFromTable) {
                    if (isItemInInvoice(itemID)) {
                        JOptionPane.showMessageDialog(this, "The Selecting Item is Already Added!");
                    } else {
                        int newQty = qtyFromTable - qtyToAdd;
                        double newprice = (double) (price * qtyToAdd);
                        tblPro.setValueAt(String.valueOf(newQty), selectedRow, 3);
                        dataModelInvoice.addRow(new Object[]{itemID, name, category, String.valueOf(qtyToAdd), newprice});

                        total += (price * qtyToAdd);
                        txtTotal.setText(String.valueOf(total));
                    }
                } else {
                    JOptionPane.showMessageDialog(this, "Quantity to add exceeds the available quantity in stock.");
                }

            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(this, "Invalid Quantity Format!");
            }
        } else {
            JOptionPane.showMessageDialog(this, "Please Select A Product First!");
        }
    }//GEN-LAST:event_btnAddActionPerformed

    private boolean dataLoaded = false;
    private void btnViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewActionPerformed
        if (!dataLoaded) {
            try {
                Class.forName("com.mysql.cj.jdbc.Driver");
                try (Connection con = DatabaseConnector.connect()) {
                    Statement st = con.createStatement();
                    String sql = "select * from products";
                    ResultSet rs = st.executeQuery(sql);

                    while (rs.next()) {
                        String id = String.valueOf(rs.getInt("itemid"));
                        String name = rs.getString("name");
                        String category = rs.getString("category");
                        String qty = rs.getString("qty");
                        String price = rs.getString("price");
                        String tbData[] = {id, name, category, qty, price};
                        DefaultTableModel tblModel = (DefaultTableModel) tblPro.getModel();
                        tblModel.addRow(tbData);
                    }
                }
                dataLoaded = true;
            } catch (ClassNotFoundException | SQLException e) {
                System.out.println(e.getMessage());
            }
        } else {
            JOptionPane.showMessageDialog(this, "Products Are Already Loaded!");
        }
    }//GEN-LAST:event_btnViewActionPerformed

    private void btnRemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoveActionPerformed
        int selectedRow = tblInv.getSelectedRow();
        if (selectedRow != -1) {
            double price = (double) tblInv.getValueAt(selectedRow, 4);
            dataModelInvoice.removeRow(selectedRow);

            total -= price;
            txtTotal.setText(String.valueOf(total));
        } else {
            JOptionPane.showMessageDialog(this, "Please Select A Product!");
        }
    }//GEN-LAST:event_btnRemoveActionPerformed

    private void btnCalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalActionPerformed
        if (txtTotal.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Invoice Table is Empty!");
        } else if (txtPay.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Please Add the Payment!");
        } else {
            double totalchk = Double.parseDouble(txtTotal.getText());
            double paychk = Double.parseDouble(txtPay.getText());
            if (paychk < totalchk) {
                JOptionPane.showMessageDialog(this, "Payment Can't Be Less Value Than Total!\nPlease Enter Higher Value Than Total!");
            } else {
                if (txtPay.getText().equals("")) {
                    JOptionPane.showMessageDialog(this, "Payment Field is Empty!\nPlease Enter The Payment Value!");
                } else {
                    try {
                        double totalAmount = Double.parseDouble(txtTotal.getText());
                        double paymentAmount = Double.parseDouble(txtPay.getText());
                        double balance = totalAmount - paymentAmount;

                        txtBal.setText(String.valueOf(balance));
                    } catch (NumberFormatException e) {
                        JOptionPane.showMessageDialog(this, "Please Enter Valid Numeric Values!");
                    }
                }
            }
        }
    }//GEN-LAST:event_btnCalActionPerformed

    private void clearInvoice() {
        DefaultTableModel model = (DefaultTableModel) tblPro.getModel();
        model.setRowCount(0);
        txtTotal.setText("");
        txtPay.setText("");
        txtBal.setText("");
    }

    private void btnPayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPayActionPerformed
        if (txtBal.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Before Make Payment,\nCalculate the Balance!");
        } else {
            if (dataModelInvoice.getRowCount() > 0) {
                try (Connection conn = DatabaseConnector.connect()) {
                    conn.setAutoCommit(false);

                    String insertSalesSQL = "INSERT INTO sales (total, payment, balance) VALUES (?, ?, ?)";
                    try (PreparedStatement insertSalesStatement = conn.prepareStatement(insertSalesSQL, Statement.RETURN_GENERATED_KEYS)) {

                        double totalSaleAmount = 0.0;

                        for (int i = 0; i < dataModelInvoice.getRowCount(); i++) {
                            double price = (double) dataModelInvoice.getValueAt(i, 4);
                            totalSaleAmount += price;
                        }

                        double paymentAmount = Double.parseDouble(txtPay.getText());
                        double balance = totalSaleAmount - paymentAmount;

                        insertSalesStatement.setDouble(1, totalSaleAmount);
                        insertSalesStatement.setDouble(2, paymentAmount);
                        insertSalesStatement.setDouble(3, balance);

                        insertSalesStatement.executeUpdate();

                        try (ResultSet generatedKeys = insertSalesStatement.getGeneratedKeys()) {
                            int salesID = -1;
                            if (generatedKeys.next()) {
                                salesID = generatedKeys.getInt(1);
                            }

                            String insertSaleItemsSQL = "INSERT INTO saleItems (saleID, itemID, quantity, price) VALUES (?, ?, ?, ?)";
                            try (PreparedStatement insertSaleItemsStatement = conn.prepareStatement(insertSaleItemsSQL)) {

                                for (int i = 0; i < dataModelInvoice.getRowCount(); i++) {
                                    String itemID = (String) dataModelInvoice.getValueAt(i, 0);
                                    int quantity = Integer.parseInt((String) dataModelInvoice.getValueAt(i, 3));
                                    double price = (double) dataModelInvoice.getValueAt(i, 4);

                                    insertSaleItemsStatement.setInt(1, salesID);
                                    insertSaleItemsStatement.setString(2, itemID);
                                    insertSaleItemsStatement.setInt(3, quantity);
                                    insertSaleItemsStatement.setDouble(4, price);

                                    insertSaleItemsStatement.executeUpdate();

                                    String updateProductsSQL = "UPDATE products SET qty = qty - ? WHERE itemid = ?";
                                    try (PreparedStatement updateProductsStatement = conn.prepareStatement(updateProductsSQL)) {
                                        updateProductsStatement.setInt(1, quantity);
                                        updateProductsStatement.setString(2, itemID);
                                        updateProductsStatement.executeUpdate();
                                    }
                                }
                            }
                        }
                    }
                    conn.commit();

                    clearInvoice();
                    JOptionPane.showMessageDialog(this, "Payment successful!");
                } catch (SQLException | NumberFormatException e) {
                    JOptionPane.showMessageDialog(this, "Payment unsuccessful! Please check the fields.");
                }
            } else {
                JOptionPane.showMessageDialog(this, "No items in the invoice table. Please add products first!");
            }
        }
    }//GEN-LAST:event_btnPayActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnExitActionPerformed

    private void btnPrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrintActionPerformed
        String path = "";
        JFileChooser j = new JFileChooser();
        j.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        int x = j.showSaveDialog(this);

        if (x == JFileChooser.APPROVE_OPTION) {
            path = j.getSelectedFile().getPath();
        }
        Document doc = new Document();
        try {
            PdfWriter.getInstance(doc, new FileOutputStream(path + "inv.pdf"));
            doc.open();
            PdfPTable tbl = new PdfPTable(4);

            tbl.addCell("ItemID");
            tbl.addCell("Name");
            tbl.addCell("Category");
            tbl.addCell("Quantity");
            tbl.addCell("Price($)");

            for (int i = 0; i < tblInv.getRowCount(); i++) {

                String id = tblInv.getValueAt(i, 0).toString();
                String name = tblInv.getValueAt(i, 1).toString();
                String cat = tblInv.getValueAt(i, 2).toString();
                String qty = tblInv.getValueAt(i, 3).toString();
                String price = tblInv.getValueAt(i, 4).toString();

                tbl.addCell(id);
                tbl.addCell(name);
                tbl.addCell(cat);
                tbl.addCell(qty);
                tbl.addCell(price);

            }
            doc.add(tbl);
            JOptionPane.showMessageDialog(null, "PDF Generated Successfully!");

        } catch (DocumentException | FileNotFoundException e) {
            JOptionPane.showMessageDialog(null, "Error Occured!");
        }
    }//GEN-LAST:event_btnPrintActionPerformed

    private void txtPayKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPayKeyPressed
        char c = evt.getKeyChar();
        if (Character.isDigit(c) || (c == KeyEvent.VK_BACK_SPACE) || (c == KeyEvent.VK_PERIOD) || (c == KeyEvent.VK_DECIMAL)) {
            lblPayErr.setText("");
            txtPay.setEditable(true);
        } else {
            txtPay.setEditable(false);
            lblPayErr.setText("Please Input Numbers Only!");
        }
    }//GEN-LAST:event_txtPayKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CashierView.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CashierView.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CashierView.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CashierView.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CashierView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnCal;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnLogin;
    private javax.swing.JButton btnPay;
    private javax.swing.JButton btnPrint;
    private javax.swing.JButton btnRef;
    private javax.swing.JButton btnRemove;
    private javax.swing.JButton btnSearch;
    private javax.swing.JButton btnView;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblBal;
    private javax.swing.JLabel lblFooter;
    private javax.swing.JLabel lblHeader;
    private javax.swing.JLabel lblInvoice;
    private javax.swing.JLabel lblPay;
    private javax.swing.JLabel lblPayErr;
    private javax.swing.JLabel lblProducts;
    private javax.swing.JLabel lblQty;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JPanel pnlBG;
    private javax.swing.JPanel pnlFooter;
    private javax.swing.JPanel pnlHeader;
    private javax.swing.JPanel pnlInvoice;
    private javax.swing.JPanel pnlProducts;
    private javax.swing.JSpinner spnQty;
    private javax.swing.JTable tblInv;
    private javax.swing.JTable tblPro;
    private javax.swing.JTextField txtBal;
    private javax.swing.JTextField txtPay;
    private javax.swing.JTextField txtSearch;
    private javax.swing.JTextField txtTotal;
    // End of variables declaration//GEN-END:variables
}
