package View;

import Controller.AccountCreateController;
import Controller.LoginController;
import Controller.ManagerController;
import Database.DatabaseConnector;
import Model.LoginModel;
import java.awt.HeadlessException;
import java.awt.event.KeyEvent;
import java.sql.Connection;
//import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
//import javax.swing.table.TableModel;

public class ManagerView extends javax.swing.JFrame {

//    private ManagerController controller;
//
//    public void setController(ManagerController controller) {
//        this.controller = controller;
//    }
    /**
     * Creates new form Manager
     */
    public ManagerView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jTextField2 = new javax.swing.JTextField();
        pnlBG = new javax.swing.JPanel();
        pnlFooter = new javax.swing.JPanel();
        lblFooter = new javax.swing.JLabel();
        pnlControl = new javax.swing.JPanel();
        btnExit = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnView = new javax.swing.JButton();
        lblQtyErr = new javax.swing.JLabel();
        lblPriceErr = new javax.swing.JLabel();
        lblIdErr = new javax.swing.JLabel();
        pnlDetails = new javax.swing.JPanel();
        btnAddNew = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        lblPrice = new javax.swing.JLabel();
        txtPrice = new javax.swing.JTextField();
        txtQty = new javax.swing.JTextField();
        txtCategory = new javax.swing.JTextField();
        txtName = new javax.swing.JTextField();
        txtItemID = new javax.swing.JTextField();
        lblId = new javax.swing.JLabel();
        lblName = new javax.swing.JLabel();
        lblCat = new javax.swing.JLabel();
        lblQty = new javax.swing.JLabel();
        btnBackLogin = new javax.swing.JButton();
        pnlProducts = new javax.swing.JPanel();
        btnCreateAcc = new javax.swing.JButton();
        btnRef = new javax.swing.JButton();
        txtSearch = new javax.swing.JTextField();
        btnSearch = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblPro = new javax.swing.JTable();
        lblTHeader = new javax.swing.JLabel();
        pnlHeader = new javax.swing.JPanel();
        lblManager = new javax.swing.JLabel();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        jTextField2.setText("jTextField2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Apple iStore - Manager Dashboard");
        setResizable(false);

        pnlBG.setBackground(new java.awt.Color(0, 0, 51));

        pnlFooter.setBackground(new java.awt.Color(51, 102, 255));

        lblFooter.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        lblFooter.setForeground(new java.awt.Color(255, 255, 255));
        lblFooter.setText("Apple Technologies USA");

        javax.swing.GroupLayout pnlFooterLayout = new javax.swing.GroupLayout(pnlFooter);
        pnlFooter.setLayout(pnlFooterLayout);
        pnlFooterLayout.setHorizontalGroup(
            pnlFooterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlFooterLayout.createSequentialGroup()
                .addGap(401, 401, 401)
                .addComponent(lblFooter)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlFooterLayout.setVerticalGroup(
            pnlFooterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlFooterLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblFooter)
                .addContainerGap())
        );

        pnlControl.setBackground(new java.awt.Color(0, 153, 255));

        btnExit.setFont(new java.awt.Font("Segoe UI", 3, 13)); // NOI18N
        btnExit.setForeground(new java.awt.Color(0, 51, 255));
        btnExit.setText("Exit");
        btnExit.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });

        btnUpdate.setFont(new java.awt.Font("Segoe UI", 3, 13)); // NOI18N
        btnUpdate.setForeground(new java.awt.Color(0, 51, 255));
        btnUpdate.setText("Update Product");
        btnUpdate.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        btnDelete.setFont(new java.awt.Font("Segoe UI", 3, 13)); // NOI18N
        btnDelete.setForeground(new java.awt.Color(255, 0, 0));
        btnDelete.setText("Delete Product");
        btnDelete.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        btnView.setFont(new java.awt.Font("Segoe UI", 3, 13)); // NOI18N
        btnView.setForeground(new java.awt.Color(0, 51, 255));
        btnView.setText("View Products");
        btnView.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewActionPerformed(evt);
            }
        });

        lblQtyErr.setFont(new java.awt.Font("Consolas", 1, 13)); // NOI18N
        lblQtyErr.setForeground(new java.awt.Color(0, 0, 204));
        lblQtyErr.setText("                    ");

        lblPriceErr.setFont(new java.awt.Font("Consolas", 1, 13)); // NOI18N
        lblPriceErr.setForeground(new java.awt.Color(0, 0, 204));
        lblPriceErr.setText("                 ");

        lblIdErr.setFont(new java.awt.Font("Consolas", 1, 13)); // NOI18N
        lblIdErr.setForeground(new java.awt.Color(0, 0, 204));
        lblIdErr.setText("                 ");

        pnlDetails.setBackground(new java.awt.Color(51, 102, 255));

        btnAddNew.setFont(new java.awt.Font("Segoe UI", 3, 13)); // NOI18N
        btnAddNew.setForeground(new java.awt.Color(0, 51, 255));
        btnAddNew.setText("Add New Product");
        btnAddNew.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnAddNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddNewActionPerformed(evt);
            }
        });

        btnClear.setFont(new java.awt.Font("Segoe UI", 3, 13)); // NOI18N
        btnClear.setForeground(new java.awt.Color(0, 51, 255));
        btnClear.setText("Clear");
        btnClear.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });

        lblPrice.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblPrice.setForeground(new java.awt.Color(255, 255, 255));
        lblPrice.setText("Price ($) :");

        txtPrice.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtPriceKeyPressed(evt);
            }
        });

        txtQty.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtQtyKeyPressed(evt);
            }
        });

        txtItemID.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtItemIDKeyPressed(evt);
            }
        });

        lblId.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblId.setForeground(new java.awt.Color(255, 255, 255));
        lblId.setText("Item ID :");

        lblName.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblName.setForeground(new java.awt.Color(255, 255, 255));
        lblName.setText("Name :");

        lblCat.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblCat.setForeground(new java.awt.Color(255, 255, 255));
        lblCat.setText("Category :");

        lblQty.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblQty.setForeground(new java.awt.Color(255, 255, 255));
        lblQty.setText("Quantity :");

        javax.swing.GroupLayout pnlDetailsLayout = new javax.swing.GroupLayout(pnlDetails);
        pnlDetails.setLayout(pnlDetailsLayout);
        pnlDetailsLayout.setHorizontalGroup(
            pnlDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlDetailsLayout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addGroup(pnlDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblId)
                    .addComponent(lblCat)
                    .addComponent(lblName)
                    .addComponent(lblQty)
                    .addGroup(pnlDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(btnClear, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblPrice, javax.swing.GroupLayout.Alignment.TRAILING)))
                .addGap(18, 18, 18)
                .addGroup(pnlDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtName)
                    .addComponent(txtItemID)
                    .addComponent(txtCategory)
                    .addComponent(txtQty)
                    .addComponent(txtPrice)
                    .addComponent(btnAddNew, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14))
        );
        pnlDetailsLayout.setVerticalGroup(
            pnlDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlDetailsLayout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addGroup(pnlDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblId)
                    .addComponent(txtItemID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblName))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCat)
                    .addComponent(txtCategory, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtQty, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblQty))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPrice))
                .addGap(18, 18, 18)
                .addGroup(pnlDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddNew)
                    .addComponent(btnClear))
                .addGap(15, 15, 15))
        );

        btnBackLogin.setFont(new java.awt.Font("Segoe UI", 3, 13)); // NOI18N
        btnBackLogin.setForeground(new java.awt.Color(0, 51, 255));
        btnBackLogin.setText("Back to Login");
        btnBackLogin.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnBackLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackLoginActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlControlLayout = new javax.swing.GroupLayout(pnlControl);
        pnlControl.setLayout(pnlControlLayout);
        pnlControlLayout.setHorizontalGroup(
            pnlControlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlControlLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(pnlDetails, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlControlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlControlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(pnlControlLayout.createSequentialGroup()
                            .addComponent(btnBackLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(pnlControlLayout.createSequentialGroup()
                            .addComponent(lblIdErr, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(btnView, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(pnlControlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(lblQtyErr, javax.swing.GroupLayout.DEFAULT_SIZE, 226, Short.MAX_VALUE)
                        .addComponent(lblPriceErr, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlControlLayout.setVerticalGroup(
            pnlControlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlControlLayout.createSequentialGroup()
                .addGroup(pnlControlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(pnlControlLayout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(pnlControlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnUpdate)
                            .addComponent(btnDelete)
                            .addComponent(btnView)
                            .addComponent(lblIdErr))
                        .addGroup(pnlControlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlControlLayout.createSequentialGroup()
                                .addGap(66, 66, 66)
                                .addComponent(lblQtyErr)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblPriceErr)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlControlLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(pnlControlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(btnBackLogin)
                                    .addComponent(btnExit)))))
                    .addGroup(pnlControlLayout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(pnlDetails, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        pnlProducts.setBackground(new java.awt.Color(102, 153, 255));

        btnCreateAcc.setFont(new java.awt.Font("Segoe UI", 3, 13)); // NOI18N
        btnCreateAcc.setForeground(new java.awt.Color(0, 51, 255));
        btnCreateAcc.setText("Create New Account");
        btnCreateAcc.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnCreateAcc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateAccActionPerformed(evt);
            }
        });

        btnRef.setFont(new java.awt.Font("Segoe UI", 3, 13)); // NOI18N
        btnRef.setForeground(new java.awt.Color(0, 51, 255));
        btnRef.setText("Refresh");
        btnRef.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnRef.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefActionPerformed(evt);
            }
        });

        btnSearch.setFont(new java.awt.Font("Segoe UI", 3, 13)); // NOI18N
        btnSearch.setForeground(new java.awt.Color(0, 51, 255));
        btnSearch.setText("Search");
        btnSearch.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        tblPro.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 12)); // NOI18N
        tblPro.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ItemID", "Name", "Category", "Quantity", "Price($)"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblPro.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tblPro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblProMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tblPro);

        lblTHeader.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        lblTHeader.setForeground(new java.awt.Color(255, 255, 255));
        lblTHeader.setText("Product Details Table");

        javax.swing.GroupLayout pnlProductsLayout = new javax.swing.GroupLayout(pnlProducts);
        pnlProducts.setLayout(pnlProductsLayout);
        pnlProductsLayout.setHorizontalGroup(
            pnlProductsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlProductsLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(pnlProductsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlProductsLayout.createSequentialGroup()
                        .addComponent(lblTHeader)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlProductsLayout.createSequentialGroup()
                        .addGroup(pnlProductsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane3)
                            .addGroup(pnlProductsLayout.createSequentialGroup()
                                .addComponent(btnCreateAcc, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnRef, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(19, 19, 19))))
        );
        pnlProductsLayout.setVerticalGroup(
            pnlProductsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlProductsLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(pnlProductsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCreateAcc)
                    .addComponent(btnRef)
                    .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSearch))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblTHeader)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        pnlHeader.setBackground(new java.awt.Color(0, 102, 255));

        lblManager.setFont(new java.awt.Font("Segoe UI", 1, 17)); // NOI18N
        lblManager.setForeground(new java.awt.Color(255, 255, 255));
        lblManager.setText("iStore - Manager Dashboard");

        javax.swing.GroupLayout pnlHeaderLayout = new javax.swing.GroupLayout(pnlHeader);
        pnlHeader.setLayout(pnlHeaderLayout);
        pnlHeaderLayout.setHorizontalGroup(
            pnlHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlHeaderLayout.createSequentialGroup()
                .addGap(361, 361, 361)
                .addComponent(lblManager)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlHeaderLayout.setVerticalGroup(
            pnlHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlHeaderLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblManager)
                .addContainerGap())
        );

        javax.swing.GroupLayout pnlBGLayout = new javax.swing.GroupLayout(pnlBG);
        pnlBG.setLayout(pnlBGLayout);
        pnlBGLayout.setHorizontalGroup(
            pnlBGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBGLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlBGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlHeader, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlProducts, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlControl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlFooter, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        pnlBGLayout.setVerticalGroup(
            pnlBGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBGLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlHeader, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlProducts, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlControl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(pnlFooter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlBG, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlBG, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        getAccessibleContext().setAccessibleName("iStore - Manager Dashboard");

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        //run the 'performSearch' method
        performSearch();
    }

    private void performSearch() {
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            try (Connection con = DatabaseConnector.connect()) {
                //make the sql command
                String sql = "SELECT * FROM products WHERE name LIKE ? OR itemid LIKE ? OR category LIKE ?";
                try (PreparedStatement ps = con.prepareStatement(sql)) {
                    ps.setString(1, "%" + txtSearch.getText() + "%");
                    ps.setString(2, "%" + txtSearch.getText() + "%");
                    ps.setString(3, "%" + txtSearch.getText() + "%");

                    //execute the sql command
                    ResultSet rs = ps.executeQuery();

                    DefaultTableModel tblModel = (DefaultTableModel) tblPro.getModel();
                    tblModel.setRowCount(0);

                    while (rs.next()) {
                        String id = String.valueOf(rs.getInt("ItemID"));
                        String name = rs.getString("Name");
                        String category = rs.getString("Category");
                        String qty = rs.getString("qty");
                        String price = rs.getString("Price");

                        String tbData[] = {id, name, category, qty, price};
                        tblModel.addRow(tbData);
                    }
                }
            }
        } catch (ClassNotFoundException | SQLException e) {
            JOptionPane.showMessageDialog(this, "An error occurred while searching products!", "Error", JOptionPane.ERROR_MESSAGE);

        }
    }//GEN-LAST:event_btnSearchActionPerformed

    private void btnRefActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefActionPerformed
        //show a new manager dashboard & close the present
        ManagerView manager = new ManagerView();
        manager.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnRefActionPerformed

    private void btnCreateAccActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateAccActionPerformed
        AccountCreateView accountcreate = new AccountCreateView();
        accountcreate.setVisible(true);
        AccountCreateController accountcontroller = new AccountCreateController(accountcreate);
        accountcreate.setController(accountcontroller);
        this.dispose();
    }//GEN-LAST:event_btnCreateAccActionPerformed

    private void btnBackLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackLoginActionPerformed
        LoginView login = new LoginView();
        login.setVisible(true);

        LoginModel loginModel = new LoginModel();

        LoginController logincontroller = new LoginController(login, loginModel);
        logincontroller.initializeController();
        this.dispose();
    }//GEN-LAST:event_btnBackLoginActionPerformed

    private void txtItemIDKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtItemIDKeyPressed
        char c = evt.getKeyChar();
        if (Character.isDigit(c) || (c == KeyEvent.VK_BACK_SPACE)) {
            lblIdErr.setText("");
            txtItemID.setEditable(true);
        } else {
            txtItemID.setEditable(false);
            lblIdErr.setText("ItemID Can't be a String!");
        }
    }//GEN-LAST:event_txtItemIDKeyPressed

    private void txtQtyKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtQtyKeyPressed
        char c = evt.getKeyChar();
        if (Character.isDigit(c) || (c == KeyEvent.VK_BACK_SPACE)) {
            lblQtyErr.setText("");
            txtQty.setEditable(true);
        } else {
            txtQty.setEditable(false);
            lblQtyErr.setText("Quantity Can't be a String!");
        }
    }//GEN-LAST:event_txtQtyKeyPressed

    private void txtPriceKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPriceKeyPressed
        char c = evt.getKeyChar();
        if (Character.isDigit(c) || (c == KeyEvent.VK_BACK_SPACE) || (c == KeyEvent.VK_PERIOD) || (c == KeyEvent.VK_DECIMAL)) {
            lblPriceErr.setText("");
            txtPrice.setEditable(true);
        } else {
            txtPrice.setEditable(false);
            lblPriceErr.setText("Price Can't be a String!");
        }
    }//GEN-LAST:event_txtPriceKeyPressed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        txtItemID.setText("");
        txtName.setText("");
        txtCategory.setText("");
        txtQty.setText("");
        txtPrice.setText("");
        lblQtyErr.setText("");
        lblPriceErr.setText("");
        lblIdErr.setText("");
    }//GEN-LAST:event_btnClearActionPerformed

    private void btnAddNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddNewActionPerformed
        if (txtItemID.getText().equals("") || txtName.getText().equals("") || txtCategory.getText().equals("") || txtQty.getText().equals("") || txtPrice.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Some Fields Are Empty!\nCheck The Fields!");
        } else {
            try {
                Class.forName("com.mysql.cj.jdbc.Driver");
                Connection con = DatabaseConnector.connect();

                if (isItemIDExists(con, txtItemID.getText())) {
                    JOptionPane.showMessageDialog(this, "ItemID Already Exists!\nPlease Add The Correct ID!");
                } else if (isProductNameExists(con, txtName.getText())) {
                    JOptionPane.showMessageDialog(this, "Product Name Already Exists!\nPlease Add The Correct Name!");
                } else {
                    Statement st = con.createStatement();

                    String itemid = txtItemID.getText();
                    String name = txtName.getText();
                    String category = txtCategory.getText();
                    String qty = txtQty.getText();
                    String price = txtPrice.getText();

                    boolean b = st.execute("insert into products(itemid, name, category, qty, price) values('" + itemid + "','" + name + "','" + category + "','" + qty + "','" + price + "')");
                    if (!b) {
                        JOptionPane.showMessageDialog(this, "Product Added Successfully!");

                        DefaultTableModel tblModel = (DefaultTableModel) tblPro.getModel();
                        String tbData[] = {itemid, name, category, qty, price};
                        tblModel.addRow(tbData);
                    } else {
                        JOptionPane.showMessageDialog(this, "Error! Try Again!");
                    }
                }
                con.close();
            } catch (HeadlessException | ClassNotFoundException | SQLException e) {
                JOptionPane.showMessageDialog(this, e);
            }
        }
    }

    private boolean isItemIDExists(Connection con, String itemID) throws SQLException {
        String checkQuery = "SELECT COUNT(*) FROM products WHERE itemid = ?";
        try (PreparedStatement ps = con.prepareStatement(checkQuery)) {
            ps.setString(1, itemID);
            try (ResultSet rs = ps.executeQuery()) {
                if (rs.next()) {
                    int count = rs.getInt(1);
                    return count > 0;
                }
            }
        }
        return false;
    }//GEN-LAST:event_btnAddNewActionPerformed

    private void btnViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewActionPerformed
        if (!dataLoaded) {
            try {
                Class.forName("com.mysql.cj.jdbc.Driver");
                Connection con = DatabaseConnector.connect();
                Statement st = con.createStatement();
                String sql = "select * from products";
                ResultSet rs = st.executeQuery(sql);

                while (rs.next()) {
                    //get values from text boxes
                    String id = String.valueOf(rs.getInt("itemid"));
                    String name = rs.getString("name");
                    String category = rs.getString("category");
                    String qty = rs.getString("qty");
                    String price = rs.getString("price");

                    String tbData[] = {id, name, category, qty, price};

                    DefaultTableModel tblModel = (DefaultTableModel) tblPro.getModel();
                    tblModel.addRow(tbData);
                }
                con.close();
                dataLoaded = true;
            } catch (ClassNotFoundException | SQLException e) {
                System.out.println(e.getMessage());
            }
        } else {
            JOptionPane.showMessageDialog(this, "Products Are Already Loaded!");
        }
    }//GEN-LAST:event_btnViewActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        DefaultTableModel tblModel = (DefaultTableModel) tblPro.getModel();
        int selectedRow = tblPro.getSelectedRow();
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Please select a row to delete.", "No Row Selected", JOptionPane.WARNING_MESSAGE);
            return;
        }

        int id = Integer.parseInt(tblModel.getValueAt(selectedRow, 0).toString());

        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con = DatabaseConnector.connect();

            try (Statement st = con.createStatement()) {
                int userChoice = JOptionPane.showConfirmDialog(this, "Are you sure you want to delete the selected row?", "Confirm Deletion", JOptionPane.YES_NO_OPTION);
                if (userChoice == JOptionPane.YES_OPTION) {
                    try (PreparedStatement ps = con.prepareStatement("DELETE FROM products WHERE itemid = ?")) {
                        ps.setInt(1, id);
                        int rowsAffected = ps.executeUpdate();
                        if (rowsAffected > 0) {
                            JOptionPane.showMessageDialog(this, "Selected product deleted successfully!");
                            tblModel.removeRow(selectedRow);
                        } else {
                            JOptionPane.showMessageDialog(this, "Failed to delete the selected product.", "Error", JOptionPane.ERROR_MESSAGE);
                        }
                    }
                }
            }
        } catch (HeadlessException | ClassNotFoundException | SQLException e) {
            //if shows this message 'drop the foreign key' in saleitems table
            JOptionPane.showMessageDialog(this, "An error occurred while delete the selected product!", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        int selectedRowIndex = tblPro.getSelectedRow();

        if (selectedRowIndex == -1) {
            JOptionPane.showMessageDialog(this, "Please Select a Row to Update!");
            return;
        }

        int id = Integer.parseInt(tblPro.getValueAt(selectedRowIndex, 0).toString());

        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con = DatabaseConnector.connect();

            if (isItemIDExists(con, txtItemID.getText(), id)) {
                JOptionPane.showMessageDialog(this, "ItemID is Already Exists!\nPlease Add The Correct ItemID!");
            } else {
                String updateQuery = "UPDATE products SET itemid=?, name=?, category=?, qty=?, price=? WHERE itemid=?";
                try (PreparedStatement ps = con.prepareStatement(updateQuery)) {

                    ps.setString(1, txtItemID.getText());
                    ps.setString(2, txtName.getText());
                    ps.setString(3, txtCategory.getText());
                    ps.setString(4, txtQty.getText());
                    ps.setString(5, txtPrice.getText());
                    ps.setInt(6, id);

                    int rowsAffected = ps.executeUpdate();
                    if (rowsAffected > 0) {
                        JOptionPane.showMessageDialog(this, "Product Updated Successfully!");

                        DefaultTableModel tblModel = (DefaultTableModel) tblPro.getModel();
                        tblModel.setValueAt(txtItemID.getText(), selectedRowIndex, 0);
                        tblModel.setValueAt(txtName.getText(), selectedRowIndex, 1);
                        tblModel.setValueAt(txtCategory.getText(), selectedRowIndex, 2);
                        tblModel.setValueAt(txtQty.getText(), selectedRowIndex, 3);
                        tblModel.setValueAt(txtPrice.getText(), selectedRowIndex, 4);
                    } else {
                        JOptionPane.showMessageDialog(this, "No data updated!\nCheck Inputs!");
                    }
                }
            }
            con.close();
        } catch (HeadlessException | ClassNotFoundException | SQLException e) {
            JOptionPane.showMessageDialog(this, "An Error Occurred While Updating The Product!", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    private boolean isItemIDExists(Connection con, String newItemID, int currentID) throws SQLException {
        String checkQuery = "SELECT COUNT(*) FROM products WHERE itemid = ? AND itemid != ?";
        try (PreparedStatement ps = con.prepareStatement(checkQuery)) {
            ps.setString(1, newItemID);
            ps.setInt(2, currentID);
            try (ResultSet rs = ps.executeQuery()) {
                if (rs.next()) {
                    int count = rs.getInt(1);
                    return count > 0;
                }
            }
        }
        return false;
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnExitActionPerformed

    private void tblProMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblProMouseClicked
        DefaultTableModel tblModel = (DefaultTableModel) tblPro.getModel();

        int selectedRow = tblPro.getSelectedRow();
        if (selectedRow == -1) {
            return;
        }

        int id = Integer.parseInt(tblModel.getValueAt(selectedRow, 0).toString());

        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            try (Connection con = DatabaseConnector.connect(); Statement st = con.createStatement(); ResultSet res = st.executeQuery("SELECT * FROM products WHERE itemid=" + id)) {

                if (res.next()) {
                    txtItemID.setText(Integer.toString(res.getInt("itemid")));
                    txtName.setText(res.getString("name"));
                    txtCategory.setText(res.getString("category"));
                    txtQty.setText(res.getString("qty"));
                    txtPrice.setText(res.getString("price"));
                } else {
                    JOptionPane.showMessageDialog(this, "No data found for the selected product ID.", "No Data Found", JOptionPane.INFORMATION_MESSAGE);
                }
            }
        } catch (HeadlessException | ClassNotFoundException | SQLException e) {
            JOptionPane.showMessageDialog(this, "An error occurred while retrieving product data.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_tblProMouseClicked

    private boolean dataLoaded = false;

    private boolean isProductNameExists(Connection con, String productName) throws SQLException {
        String checkQuery = "SELECT COUNT(*) FROM products WHERE name = ?";
        try (PreparedStatement ps = con.prepareStatement(checkQuery)) {
            ps.setString(1, productName);
            try (ResultSet rs = ps.executeQuery()) {
                if (rs.next()) {
                    int count = rs.getInt(1);
                    return count > 0;
                }
            }
        }
        return false;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManagerView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManagerView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManagerView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManagerView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ManagerView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddNew;
    private javax.swing.JButton btnBackLogin;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnCreateAcc;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnRef;
    private javax.swing.JButton btnSearch;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JButton btnView;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JLabel lblCat;
    private javax.swing.JLabel lblFooter;
    private javax.swing.JLabel lblId;
    private javax.swing.JLabel lblIdErr;
    private javax.swing.JLabel lblManager;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblPrice;
    private javax.swing.JLabel lblPriceErr;
    private javax.swing.JLabel lblQty;
    private javax.swing.JLabel lblQtyErr;
    private javax.swing.JLabel lblTHeader;
    private javax.swing.JPanel pnlBG;
    private javax.swing.JPanel pnlControl;
    private javax.swing.JPanel pnlDetails;
    private javax.swing.JPanel pnlFooter;
    private javax.swing.JPanel pnlHeader;
    private javax.swing.JPanel pnlProducts;
    private javax.swing.JTable tblPro;
    private javax.swing.JTextField txtCategory;
    private javax.swing.JTextField txtItemID;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtPrice;
    private javax.swing.JTextField txtQty;
    private javax.swing.JTextField txtSearch;
    // End of variables declaration//GEN-END:variables
}
